# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_short',
            field=models.TextField(blank=True, null=True, verbose_name='Short Content (to be shown in home)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_home',
            field=models.ImageField(blank=True, help_text='Load as 586x313', null=True, upload_to='article/image/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Match'),
        ),
    ]
