# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='is_domain_team',
            field=models.BooleanField(verbose_name='is the main team of the domain'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(),
        ),
    ]
