# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0016_season_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSeasonGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('draws', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('goals_for', models.IntegerField(blank=True, null=True)),
                ('goals_against', models.IntegerField(blank=True, null=True)),
                ('goals_difference', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('group', models.CharField(max_length=1)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Team')),
            ],
            options={
                'ordering': ['group', 'position'],
            },
        ),
        migrations.RemoveField(
            model_name='teamgroupstats',
            name='teamseason_ptr',
        ),
        migrations.DeleteModel(
            name='TeamGroupStats',
        ),
    ]
