# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160403_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'matches'},
        ),
        migrations.AddField(
            model_name='stadium',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Berlin'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
