# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160626_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_in_phase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='penalties_team_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='penalties_team_b',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
