# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160523_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='season/og/'),
        ),
        migrations.AddField(
            model_name='season',
            name='groups_og_image',
            field=models.ImageField(blank=True, null=True, upload_to='season/groups_og/'),
        ),
        migrations.AddField(
            model_name='season',
            name='results_image',
            field=models.ImageField(blank=True, null=True, upload_to='season/results/'),
        ),
    ]
