# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160524_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='indicates weather the Match is published or not'),
        ),
        migrations.AlterField(
            model_name='season',
            name='results_image',
            field=models.ImageField(blank=True, null=True, upload_to='season/results/', verbose_name='Results OG image'),
        ),
    ]
