# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160626_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='final_phase_og_image',
            field=models.ImageField(blank=True, null=True, upload_to='season/final_phase_og/'),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_in_season',
            field=models.CharField(blank=True, choices=[('fase-de-grupo-partido-1', 'Fase de grupo - Partido 1'), ('fase-de-grupo-partido-2', 'Fase de grupo - Partido 2'), ('fase-de-grupo-partido-3', 'Fase de grupo - Partido 3'), ('ronda-de-16', 'Ronda de 16'), ('cuartos-de-final', 'Cuartos de final'), ('semi-final', 'Semi-final'), ('final', 'Final'), ('partido-tercer-puesto', 'Partido tercer Puesto'), ('fecha-1', 'Fecha 1'), ('fecha-2', 'Fecha 2'), ('fecha-3', 'Fecha 3'), ('fecha-4', 'Fecha 4'), ('fecha-5', 'Fecha 5'), ('fecha-6', 'Fecha 6'), ('fecha-7', 'Fecha 7'), ('fecha-8', 'Fecha 8'), ('fecha-9', 'Fecha 9'), ('fecha-10', 'Fecha 10'), ('fecha-11', 'Fecha 11'), ('fecha-12', 'Fecha 12'), ('fecha-13', 'Fecha 13'), ('fecha-14', 'Fecha 14'), ('fecha-15', 'Fecha 15'), ('fecha-16', 'Fecha 16'), ('fecha-17', 'Fecha 17'), ('fecha-18', 'Fecha 18'), ('fecha-19', 'Fecha 19'), ('fecha-20', 'Fecha 20'), ('fecha-21', 'Fecha 21'), ('fecha-22', 'Fecha 22'), ('fecha-23', 'Fecha 23'), ('fecha-24', 'Fecha 24'), ('fecha-25', 'Fecha 25'), ('fecha-26', 'Fecha 26'), ('fecha-27', 'Fecha 27'), ('fecha-28', 'Fecha 28'), ('fecha-29', 'Fecha 29'), ('fecha-30', 'Fecha 30'), ('fecha-31', 'Fecha 31'), ('fecha-32', 'Fecha 32'), ('fecha-33', 'Fecha 33'), ('fecha-34', 'Fecha 34'), ('fecha-35', 'Fecha 35'), ('fecha-36', 'Fecha 36'), ('fecha-37', 'Fecha 37'), ('fecha-38', 'Fecha 38'), ('fecha-39', 'Fecha 39')], max_length=30, null=True),
        ),
    ]
