# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160404_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='local_time',
            new_name='time',
        ),
    ]
