# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 20:53
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160404_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Madrid'),
        ),
    ]
