# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160525_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='end_time',
            field=models.DateTimeField(verbose_name='time the match ends'),
        ),
    ]
