# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 22:49
from __future__ import unicode_literals

from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160525_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='domain',
            field=main.models.DomainField(blank=True, choices=[('aquehorajuegaargentina.com', 'aquehorajuegaargentina.com'), ('54.93.126.245:8001', '54.93.126.245:8001')], max_length=60, null=True, unique=True),
        ),
    ]
