# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160425_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_in_season',
            field=models.CharField(choices=[('Fecha 1', 'Fecha 1'), ('Fecha 2', 'Fecha 2'), ('Fecha 3', 'Fecha 3'), ('Fecha 4', 'Fecha 4'), ('Fecha 5', 'Fecha 5'), ('Fecha 6', 'Fecha 6'), ('Fecha 7', 'Fecha 7'), ('Fecha 8', 'Fecha 8'), ('Fecha 9', 'Fecha 9'), ('Fecha 10', 'Fecha 10'), ('Fecha 11', 'Fecha 11'), ('Fecha 12', 'Fecha 12'), ('Fecha 13', 'Fecha 13'), ('Fecha 14', 'Fecha 14'), ('Fecha 15', 'Fecha 15'), ('Fecha 16', 'Fecha 16'), ('Fecha 17', 'Fecha 17'), ('Fecha 18', 'Fecha 18'), ('Fecha 19', 'Fecha 19'), ('Fecha 20', 'Fecha 20'), ('Fecha 21', 'Fecha 21'), ('Fecha 22', 'Fecha 22'), ('Fecha 23', 'Fecha 23'), ('Fecha 24', 'Fecha 24'), ('Fecha 25', 'Fecha 25'), ('Fecha 26', 'Fecha 26'), ('Fecha 27', 'Fecha 27'), ('Fecha 28', 'Fecha 28'), ('Fecha 29', 'Fecha 29'), ('Fecha 30', 'Fecha 30'), ('Fecha 31', 'Fecha 31'), ('Fecha 32', 'Fecha 32'), ('Fecha 33', 'Fecha 33'), ('Fecha 34', 'Fecha 34'), ('Fecha 35', 'Fecha 35'), ('Fecha 36', 'Fecha 36'), ('Fecha 37', 'Fecha 37'), ('Fecha 38', 'Fecha 38'), ('Fecha 39', 'Fecha 39'), ('Ronda de 16', 'Ronda de 16'), ('Cuartos de final', 'Cuartos de final'), ('Semi-final', 'Semi-final'), ('Final', 'Final')], default='Fecha 1', max_length=20),
            preserve_default=False,
        ),
    ]
