# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('main', '0006_team_team_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site'),
        ),
    ]
