# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160520_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='detail_goals_team_a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='detail_goals_team_b',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
