# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160609_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-time'], 'verbose_name_plural': 'matches'},
        ),
        migrations.RemoveField(
            model_name='match',
            name='preview_part1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='preview_part2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='preview_part3',
        ),
        migrations.RemoveField(
            model_name='match',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='match',
            name='summary_sub_title',
        ),
        migrations.RemoveField(
            model_name='match',
            name='summary_title',
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='indicates weather the Article is published or not'),
        ),
    ]
