# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160521_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='html_video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
