# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160609_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamseason',
            name='goals_difference',
        ),
        migrations.RemoveField(
            model_name='teamseason',
            name='matches_played',
        ),
        migrations.RemoveField(
            model_name='teamseason',
            name='points',
        ),
        migrations.RemoveField(
            model_name='teamseasongroup',
            name='goals_difference',
        ),
        migrations.RemoveField(
            model_name='teamseasongroup',
            name='matches_played',
        ),
        migrations.RemoveField(
            model_name='teamseasongroup',
            name='points',
        ),
    ]
