# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_match_html_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='html_video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
