# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20160522_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGroupStats',
            fields=[
                ('teamseason_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.TeamSeason')),
                ('group', models.CharField(max_length=1)),
            ],
            options={
                'abstract': False,
            },
            bases=('main.teamseason',),
        ),
        migrations.AlterField(
            model_name='match',
            name='html_video',
            field=models.TextField(blank=True, help_text='&lt;iframe width=&quot;360&quot; height=&quot;203&quot; src=&quot;https://www.youtube.com/embed/CODIGO_DEL_VIDEO&quot; frameborder=&quot;0&quot; allowfullscreen=&quot;&quot;&gt;&lt;/iframe&gt;', null=True),
        ),
    ]
