# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_teamseason_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamgroupstats',
            options={'ordering': ['group', 'position']},
        ),
        migrations.AlterModelOptions(
            name='teamseason',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='season',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='indicate that this season is currently the main in the domain'),
            preserve_default=False,
        ),
    ]
