# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20160522_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
