# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('aqhj_sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainconfig',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='routeconfig',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site'),
        ),
    ]
