# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqhj_sites', '0002_auto_20160603_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainconfig',
            name='tweet',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='message to tweet'),
        ),
    ]
