# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqhj_sites', '0003_domainconfig_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/logo/'),
        ),
    ]
