# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqhj_sites', '0005_auto_20160607_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainconfig',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/favicon/'),
        ),
    ]
