# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqhj_sites', '0006_domainconfig_favicon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainconfig',
            old_name='google_analytics_script',
            new_name='extra_footer_script',
        ),
        migrations.AddField(
            model_name='domainconfig',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
