# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('aqhj_sites', '0008_auto_20160616_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectOn404',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=150)),
                ('target', models.CharField(max_length=150)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site')),
            ],
        ),
    ]
