# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqhj_sites', '0009_redirecton404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeconfig',
            name='route',
            field=models.CharField(choices=[('index', 'index'), ('match_before', 'match_before'), ('match_before_no_gis', 'match_before_no_gis'), ('past_match', 'past_match'), ('past_match_no_gis', 'past_match_no_gis'), ('last_matches', 'last_matches'), ('group_positions', 'group_positions'), ('final_phase_positions', 'final_phase_positions'), ('nl_success_confirm', 'nl_success_confirm')], max_length=60),
        ),
    ]
